#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsTrackingSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LogisticsDB")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertwarehouse(warehouse instance);
    partial void Updatewarehouse(warehouse instance);
    partial void Deletewarehouse(warehouse instance);
    partial void Insertdriver(driver instance);
    partial void Updatedriver(driver instance);
    partial void Deletedriver(driver instance);
    partial void Insertparcel_log(parcel_log instance);
    partial void Updateparcel_log(parcel_log instance);
    partial void Deleteparcel_log(parcel_log instance);
    partial void Insertparcel_route(parcel_route instance);
    partial void Updateparcel_route(parcel_route instance);
    partial void Deleteparcel_route(parcel_route instance);
    partial void Insertparcel(parcel instance);
    partial void Updateparcel(parcel instance);
    partial void Deleteparcel(parcel instance);
    partial void Insertroute(route instance);
    partial void Updateroute(route instance);
    partial void Deleteroute(route instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<warehouse> warehouses
		{
			get
			{
				return this.GetTable<warehouse>();
			}
		}
		
		public System.Data.Linq.Table<driver> drivers
		{
			get
			{
				return this.GetTable<driver>();
			}
		}
		
		public System.Data.Linq.Table<parcel_log> parcel_logs
		{
			get
			{
				return this.GetTable<parcel_log>();
			}
		}
		
		public System.Data.Linq.Table<parcel_route> parcel_routes
		{
			get
			{
				return this.GetTable<parcel_route>();
			}
		}
		
		public System.Data.Linq.Table<parcel> parcels
		{
			get
			{
				return this.GetTable<parcel>();
			}
		}
		
		public System.Data.Linq.Table<route> routes
		{
			get
			{
				return this.GetTable<route>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _email;
		
		private string _phone;
		
		private string _type;
		
		private EntitySet<parcel> _parcels;
		
		private EntitySet<parcel> _parcels1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public customer()
		{
			this._parcels = new EntitySet<parcel>(new Action<parcel>(this.attach_parcels), new Action<parcel>(this.detach_parcels));
			this._parcels1 = new EntitySet<parcel>(new Action<parcel>(this.attach_parcels1), new Action<parcel>(this.detach_parcels1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_parcel", Storage="_parcels", ThisKey="id", OtherKey="receiver_id")]
		public EntitySet<parcel> parcels
		{
			get
			{
				return this._parcels;
			}
			set
			{
				this._parcels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_parcel1", Storage="_parcels1", ThisKey="id", OtherKey="sender_id")]
		public EntitySet<parcel> parcels1
		{
			get
			{
				return this._parcels1;
			}
			set
			{
				this._parcels1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_parcels(parcel entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_parcels(parcel entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
		
		private void attach_parcels1(parcel entity)
		{
			this.SendPropertyChanging();
			entity.customer1 = this;
		}
		
		private void detach_parcels1(parcel entity)
		{
			this.SendPropertyChanging();
			entity.customer1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.warehouses")]
	public partial class warehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _contact;
		
		private string _location;
		
		private EntitySet<parcel> _parcels;
		
		private EntitySet<parcel> _parcels1;
		
		private EntitySet<route> _routes;
		
		private EntitySet<route> _routes1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncontactChanging(string value);
    partial void OncontactChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    #endregion
		
		public warehouse()
		{
			this._parcels = new EntitySet<parcel>(new Action<parcel>(this.attach_parcels), new Action<parcel>(this.detach_parcels));
			this._parcels1 = new EntitySet<parcel>(new Action<parcel>(this.attach_parcels1), new Action<parcel>(this.detach_parcels1));
			this._routes = new EntitySet<route>(new Action<route>(this.attach_routes), new Action<route>(this.detach_routes));
			this._routes1 = new EntitySet<route>(new Action<route>(this.attach_routes1), new Action<route>(this.detach_routes1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact", DbType="VarChar(255)")]
		public string contact
		{
			get
			{
				return this._contact;
			}
			set
			{
				if ((this._contact != value))
				{
					this.OncontactChanging(value);
					this.SendPropertyChanging();
					this._contact = value;
					this.SendPropertyChanged("contact");
					this.OncontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(MAX)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_parcel", Storage="_parcels", ThisKey="id", OtherKey="destination_id")]
		public EntitySet<parcel> parcels
		{
			get
			{
				return this._parcels;
			}
			set
			{
				this._parcels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_parcel1", Storage="_parcels1", ThisKey="id", OtherKey="origin_id")]
		public EntitySet<parcel> parcels1
		{
			get
			{
				return this._parcels1;
			}
			set
			{
				this._parcels1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_route", Storage="_routes", ThisKey="id", OtherKey="destination_id")]
		public EntitySet<route> routes
		{
			get
			{
				return this._routes;
			}
			set
			{
				this._routes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_route1", Storage="_routes1", ThisKey="id", OtherKey="origin_id")]
		public EntitySet<route> routes1
		{
			get
			{
				return this._routes1;
			}
			set
			{
				this._routes1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_parcels(parcel entity)
		{
			this.SendPropertyChanging();
			entity.warehouse = this;
		}
		
		private void detach_parcels(parcel entity)
		{
			this.SendPropertyChanging();
			entity.warehouse = null;
		}
		
		private void attach_parcels1(parcel entity)
		{
			this.SendPropertyChanging();
			entity.warehouse1 = this;
		}
		
		private void detach_parcels1(parcel entity)
		{
			this.SendPropertyChanging();
			entity.warehouse1 = null;
		}
		
		private void attach_routes(route entity)
		{
			this.SendPropertyChanging();
			entity.warehouse = this;
		}
		
		private void detach_routes(route entity)
		{
			this.SendPropertyChanging();
			entity.warehouse = null;
		}
		
		private void attach_routes1(route entity)
		{
			this.SendPropertyChanging();
			entity.warehouse1 = this;
		}
		
		private void detach_routes1(route entity)
		{
			this.SendPropertyChanging();
			entity.warehouse1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.drivers")]
	public partial class driver : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _phone;
		
		private int _capacity;
		
		private string _license_plate;
		
		private EntitySet<parcel_log> _parcel_logs;
		
		private EntitySet<route> _routes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncapacityChanging(int value);
    partial void OncapacityChanged();
    partial void Onlicense_plateChanging(string value);
    partial void Onlicense_plateChanged();
    #endregion
		
		public driver()
		{
			this._parcel_logs = new EntitySet<parcel_log>(new Action<parcel_log>(this.attach_parcel_logs), new Action<parcel_log>(this.detach_parcel_logs));
			this._routes = new EntitySet<route>(new Action<route>(this.attach_routes), new Action<route>(this.detach_routes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int NOT NULL")]
		public int capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license_plate", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string license_plate
		{
			get
			{
				return this._license_plate;
			}
			set
			{
				if ((this._license_plate != value))
				{
					this.Onlicense_plateChanging(value);
					this.SendPropertyChanging();
					this._license_plate = value;
					this.SendPropertyChanged("license_plate");
					this.Onlicense_plateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="driver_parcel_log", Storage="_parcel_logs", ThisKey="id", OtherKey="driver_id")]
		public EntitySet<parcel_log> parcel_logs
		{
			get
			{
				return this._parcel_logs;
			}
			set
			{
				this._parcel_logs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="driver_route", Storage="_routes", ThisKey="id", OtherKey="driver_id")]
		public EntitySet<route> routes
		{
			get
			{
				return this._routes;
			}
			set
			{
				this._routes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_parcel_logs(parcel_log entity)
		{
			this.SendPropertyChanging();
			entity.driver = this;
		}
		
		private void detach_parcel_logs(parcel_log entity)
		{
			this.SendPropertyChanging();
			entity.driver = null;
		}
		
		private void attach_routes(route entity)
		{
			this.SendPropertyChanging();
			entity.driver = this;
		}
		
		private void detach_routes(route entity)
		{
			this.SendPropertyChanging();
			entity.driver = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parcel_logs")]
	public partial class parcel_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _status;
		
		private string _location;
		
		private string _note;
		
		private System.Nullable<System.DateTime> _timestamp;
		
		private string _parcel_id;
		
		private int _driver_id;
		
		private EntityRef<driver> _driver;
		
		private EntityRef<parcel> _parcel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OntimestampChanging(System.Nullable<System.DateTime> value);
    partial void OntimestampChanged();
    partial void Onparcel_idChanging(string value);
    partial void Onparcel_idChanged();
    partial void Ondriver_idChanging(int value);
    partial void Ondriver_idChanged();
    #endregion
		
		public parcel_log()
		{
			this._driver = default(EntityRef<driver>);
			this._parcel = default(EntityRef<parcel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(255)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="VarChar(MAX)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parcel_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string parcel_id
		{
			get
			{
				return this._parcel_id;
			}
			set
			{
				if ((this._parcel_id != value))
				{
					if (this._parcel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onparcel_idChanging(value);
					this.SendPropertyChanging();
					this._parcel_id = value;
					this.SendPropertyChanged("parcel_id");
					this.Onparcel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_id", DbType="Int NOT NULL")]
		public int driver_id
		{
			get
			{
				return this._driver_id;
			}
			set
			{
				if ((this._driver_id != value))
				{
					if (this._driver.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondriver_idChanging(value);
					this.SendPropertyChanging();
					this._driver_id = value;
					this.SendPropertyChanged("driver_id");
					this.Ondriver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="driver_parcel_log", Storage="_driver", ThisKey="driver_id", OtherKey="id", IsForeignKey=true)]
		public driver driver
		{
			get
			{
				return this._driver.Entity;
			}
			set
			{
				driver previousValue = this._driver.Entity;
				if (((previousValue != value) 
							|| (this._driver.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._driver.Entity = null;
						previousValue.parcel_logs.Remove(this);
					}
					this._driver.Entity = value;
					if ((value != null))
					{
						value.parcel_logs.Add(this);
						this._driver_id = value.id;
					}
					else
					{
						this._driver_id = default(int);
					}
					this.SendPropertyChanged("driver");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parcel_parcel_log", Storage="_parcel", ThisKey="parcel_id", OtherKey="tracking_no", IsForeignKey=true)]
		public parcel parcel
		{
			get
			{
				return this._parcel.Entity;
			}
			set
			{
				parcel previousValue = this._parcel.Entity;
				if (((previousValue != value) 
							|| (this._parcel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._parcel.Entity = null;
						previousValue.parcel_logs.Remove(this);
					}
					this._parcel.Entity = value;
					if ((value != null))
					{
						value.parcel_logs.Add(this);
						this._parcel_id = value.tracking_no;
					}
					else
					{
						this._parcel_id = default(string);
					}
					this.SendPropertyChanged("parcel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parcel_routes")]
	public partial class parcel_route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _parcel_id;
		
		private int _route_id;
		
		private EntityRef<parcel> _parcel;
		
		private EntityRef<route> _route;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onparcel_idChanging(string value);
    partial void Onparcel_idChanged();
    partial void Onroute_idChanging(int value);
    partial void Onroute_idChanged();
    #endregion
		
		public parcel_route()
		{
			this._parcel = default(EntityRef<parcel>);
			this._route = default(EntityRef<route>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parcel_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string parcel_id
		{
			get
			{
				return this._parcel_id;
			}
			set
			{
				if ((this._parcel_id != value))
				{
					if (this._parcel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onparcel_idChanging(value);
					this.SendPropertyChanging();
					this._parcel_id = value;
					this.SendPropertyChanged("parcel_id");
					this.Onparcel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_route_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int route_id
		{
			get
			{
				return this._route_id;
			}
			set
			{
				if ((this._route_id != value))
				{
					if (this._route.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onroute_idChanging(value);
					this.SendPropertyChanging();
					this._route_id = value;
					this.SendPropertyChanged("route_id");
					this.Onroute_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parcel_parcel_route", Storage="_parcel", ThisKey="parcel_id", OtherKey="tracking_no", IsForeignKey=true)]
		public parcel parcel
		{
			get
			{
				return this._parcel.Entity;
			}
			set
			{
				parcel previousValue = this._parcel.Entity;
				if (((previousValue != value) 
							|| (this._parcel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._parcel.Entity = null;
						previousValue.parcel_routes.Remove(this);
					}
					this._parcel.Entity = value;
					if ((value != null))
					{
						value.parcel_routes.Add(this);
						this._parcel_id = value.tracking_no;
					}
					else
					{
						this._parcel_id = default(string);
					}
					this.SendPropertyChanged("parcel");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="route_parcel_route", Storage="_route", ThisKey="route_id", OtherKey="id", IsForeignKey=true)]
		public route route
		{
			get
			{
				return this._route.Entity;
			}
			set
			{
				route previousValue = this._route.Entity;
				if (((previousValue != value) 
							|| (this._route.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._route.Entity = null;
						previousValue.parcel_routes.Remove(this);
					}
					this._route.Entity = value;
					if ((value != null))
					{
						value.parcel_routes.Add(this);
						this._route_id = value.id;
					}
					else
					{
						this._route_id = default(int);
					}
					this.SendPropertyChanged("route");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parcels")]
	public partial class parcel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tracking_no;
		
		private decimal _weight;
		
		private string _status;
		
		private string _type;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private int _sender_id;
		
		private int _receiver_id;
		
		private int _origin_id;
		
		private int _destination_id;
		
		private EntitySet<parcel_log> _parcel_logs;
		
		private EntitySet<parcel_route> _parcel_routes;
		
		private EntityRef<warehouse> _warehouse;
		
		private EntityRef<warehouse> _warehouse1;
		
		private EntityRef<customer> _customer;
		
		private EntityRef<customer> _customer1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontracking_noChanging(string value);
    partial void Ontracking_noChanged();
    partial void OnweightChanging(decimal value);
    partial void OnweightChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onsender_idChanging(int value);
    partial void Onsender_idChanged();
    partial void Onreceiver_idChanging(int value);
    partial void Onreceiver_idChanged();
    partial void Onorigin_idChanging(int value);
    partial void Onorigin_idChanged();
    partial void Ondestination_idChanging(int value);
    partial void Ondestination_idChanged();
    #endregion
		
		public parcel()
		{
			this._parcel_logs = new EntitySet<parcel_log>(new Action<parcel_log>(this.attach_parcel_logs), new Action<parcel_log>(this.detach_parcel_logs));
			this._parcel_routes = new EntitySet<parcel_route>(new Action<parcel_route>(this.attach_parcel_routes), new Action<parcel_route>(this.detach_parcel_routes));
			this._warehouse = default(EntityRef<warehouse>);
			this._warehouse1 = default(EntityRef<warehouse>);
			this._customer = default(EntityRef<customer>);
			this._customer1 = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tracking_no", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tracking_no
		{
			get
			{
				return this._tracking_no;
			}
			set
			{
				if ((this._tracking_no != value))
				{
					this.Ontracking_noChanging(value);
					this.SendPropertyChanging();
					this._tracking_no = value;
					this.SendPropertyChanged("tracking_no");
					this.Ontracking_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Decimal(10,2) NOT NULL")]
		public decimal weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender_id", DbType="Int NOT NULL")]
		public int sender_id
		{
			get
			{
				return this._sender_id;
			}
			set
			{
				if ((this._sender_id != value))
				{
					if (this._customer1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsender_idChanging(value);
					this.SendPropertyChanging();
					this._sender_id = value;
					this.SendPropertyChanged("sender_id");
					this.Onsender_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receiver_id", DbType="Int NOT NULL")]
		public int receiver_id
		{
			get
			{
				return this._receiver_id;
			}
			set
			{
				if ((this._receiver_id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onreceiver_idChanging(value);
					this.SendPropertyChanging();
					this._receiver_id = value;
					this.SendPropertyChanged("receiver_id");
					this.Onreceiver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origin_id", DbType="Int NOT NULL")]
		public int origin_id
		{
			get
			{
				return this._origin_id;
			}
			set
			{
				if ((this._origin_id != value))
				{
					if (this._warehouse1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onorigin_idChanging(value);
					this.SendPropertyChanging();
					this._origin_id = value;
					this.SendPropertyChanged("origin_id");
					this.Onorigin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_id", DbType="Int NOT NULL")]
		public int destination_id
		{
			get
			{
				return this._destination_id;
			}
			set
			{
				if ((this._destination_id != value))
				{
					if (this._warehouse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondestination_idChanging(value);
					this.SendPropertyChanging();
					this._destination_id = value;
					this.SendPropertyChanged("destination_id");
					this.Ondestination_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parcel_parcel_log", Storage="_parcel_logs", ThisKey="tracking_no", OtherKey="parcel_id")]
		public EntitySet<parcel_log> parcel_logs
		{
			get
			{
				return this._parcel_logs;
			}
			set
			{
				this._parcel_logs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parcel_parcel_route", Storage="_parcel_routes", ThisKey="tracking_no", OtherKey="parcel_id")]
		public EntitySet<parcel_route> parcel_routes
		{
			get
			{
				return this._parcel_routes;
			}
			set
			{
				this._parcel_routes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_parcel", Storage="_warehouse", ThisKey="destination_id", OtherKey="id", IsForeignKey=true)]
		public warehouse warehouse
		{
			get
			{
				return this._warehouse.Entity;
			}
			set
			{
				warehouse previousValue = this._warehouse.Entity;
				if (((previousValue != value) 
							|| (this._warehouse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._warehouse.Entity = null;
						previousValue.parcels.Remove(this);
					}
					this._warehouse.Entity = value;
					if ((value != null))
					{
						value.parcels.Add(this);
						this._destination_id = value.id;
					}
					else
					{
						this._destination_id = default(int);
					}
					this.SendPropertyChanged("warehouse");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_parcel1", Storage="_warehouse1", ThisKey="origin_id", OtherKey="id", IsForeignKey=true)]
		public warehouse warehouse1
		{
			get
			{
				return this._warehouse1.Entity;
			}
			set
			{
				warehouse previousValue = this._warehouse1.Entity;
				if (((previousValue != value) 
							|| (this._warehouse1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._warehouse1.Entity = null;
						previousValue.parcels1.Remove(this);
					}
					this._warehouse1.Entity = value;
					if ((value != null))
					{
						value.parcels1.Add(this);
						this._origin_id = value.id;
					}
					else
					{
						this._origin_id = default(int);
					}
					this.SendPropertyChanged("warehouse1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_parcel", Storage="_customer", ThisKey="receiver_id", OtherKey="id", IsForeignKey=true)]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.parcels.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.parcels.Add(this);
						this._receiver_id = value.id;
					}
					else
					{
						this._receiver_id = default(int);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_parcel1", Storage="_customer1", ThisKey="sender_id", OtherKey="id", IsForeignKey=true)]
		public customer customer1
		{
			get
			{
				return this._customer1.Entity;
			}
			set
			{
				customer previousValue = this._customer1.Entity;
				if (((previousValue != value) 
							|| (this._customer1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer1.Entity = null;
						previousValue.parcels1.Remove(this);
					}
					this._customer1.Entity = value;
					if ((value != null))
					{
						value.parcels1.Add(this);
						this._sender_id = value.id;
					}
					else
					{
						this._sender_id = default(int);
					}
					this.SendPropertyChanged("customer1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_parcel_logs(parcel_log entity)
		{
			this.SendPropertyChanging();
			entity.parcel = this;
		}
		
		private void detach_parcel_logs(parcel_log entity)
		{
			this.SendPropertyChanging();
			entity.parcel = null;
		}
		
		private void attach_parcel_routes(parcel_route entity)
		{
			this.SendPropertyChanging();
			entity.parcel = this;
		}
		
		private void detach_parcel_routes(parcel_route entity)
		{
			this.SendPropertyChanging();
			entity.parcel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.routes")]
	public partial class route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<decimal> _distance;
		
		private System.Nullable<int> _estimated_time;
		
		private int _origin_id;
		
		private int _destination_id;
		
		private int _driver_id;
		
		private System.Nullable<System.DateTime> _assigned_at;
		
		private EntitySet<parcel_route> _parcel_routes;
		
		private EntityRef<warehouse> _warehouse;
		
		private EntityRef<driver> _driver;
		
		private EntityRef<warehouse> _warehouse1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndistanceChanging(System.Nullable<decimal> value);
    partial void OndistanceChanged();
    partial void Onestimated_timeChanging(System.Nullable<int> value);
    partial void Onestimated_timeChanged();
    partial void Onorigin_idChanging(int value);
    partial void Onorigin_idChanged();
    partial void Ondestination_idChanging(int value);
    partial void Ondestination_idChanged();
    partial void Ondriver_idChanging(int value);
    partial void Ondriver_idChanged();
    partial void Onassigned_atChanging(System.Nullable<System.DateTime> value);
    partial void Onassigned_atChanged();
    #endregion
		
		public route()
		{
			this._parcel_routes = new EntitySet<parcel_route>(new Action<parcel_route>(this.attach_parcel_routes), new Action<parcel_route>(this.detach_parcel_routes));
			this._warehouse = default(EntityRef<warehouse>);
			this._driver = default(EntityRef<driver>);
			this._warehouse1 = default(EntityRef<warehouse>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distance", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this.OndistanceChanging(value);
					this.SendPropertyChanging();
					this._distance = value;
					this.SendPropertyChanged("distance");
					this.OndistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estimated_time", DbType="Int")]
		public System.Nullable<int> estimated_time
		{
			get
			{
				return this._estimated_time;
			}
			set
			{
				if ((this._estimated_time != value))
				{
					this.Onestimated_timeChanging(value);
					this.SendPropertyChanging();
					this._estimated_time = value;
					this.SendPropertyChanged("estimated_time");
					this.Onestimated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origin_id", DbType="Int NOT NULL")]
		public int origin_id
		{
			get
			{
				return this._origin_id;
			}
			set
			{
				if ((this._origin_id != value))
				{
					if (this._warehouse1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onorigin_idChanging(value);
					this.SendPropertyChanging();
					this._origin_id = value;
					this.SendPropertyChanged("origin_id");
					this.Onorigin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_id", DbType="Int NOT NULL")]
		public int destination_id
		{
			get
			{
				return this._destination_id;
			}
			set
			{
				if ((this._destination_id != value))
				{
					if (this._warehouse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondestination_idChanging(value);
					this.SendPropertyChanging();
					this._destination_id = value;
					this.SendPropertyChanged("destination_id");
					this.Ondestination_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver_id", DbType="Int NOT NULL")]
		public int driver_id
		{
			get
			{
				return this._driver_id;
			}
			set
			{
				if ((this._driver_id != value))
				{
					if (this._driver.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondriver_idChanging(value);
					this.SendPropertyChanging();
					this._driver_id = value;
					this.SendPropertyChanged("driver_id");
					this.Ondriver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assigned_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> assigned_at
		{
			get
			{
				return this._assigned_at;
			}
			set
			{
				if ((this._assigned_at != value))
				{
					this.Onassigned_atChanging(value);
					this.SendPropertyChanging();
					this._assigned_at = value;
					this.SendPropertyChanged("assigned_at");
					this.Onassigned_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="route_parcel_route", Storage="_parcel_routes", ThisKey="id", OtherKey="route_id")]
		public EntitySet<parcel_route> parcel_routes
		{
			get
			{
				return this._parcel_routes;
			}
			set
			{
				this._parcel_routes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_route", Storage="_warehouse", ThisKey="destination_id", OtherKey="id", IsForeignKey=true)]
		public warehouse warehouse
		{
			get
			{
				return this._warehouse.Entity;
			}
			set
			{
				warehouse previousValue = this._warehouse.Entity;
				if (((previousValue != value) 
							|| (this._warehouse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._warehouse.Entity = null;
						previousValue.routes.Remove(this);
					}
					this._warehouse.Entity = value;
					if ((value != null))
					{
						value.routes.Add(this);
						this._destination_id = value.id;
					}
					else
					{
						this._destination_id = default(int);
					}
					this.SendPropertyChanged("warehouse");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="driver_route", Storage="_driver", ThisKey="driver_id", OtherKey="id", IsForeignKey=true)]
		public driver driver
		{
			get
			{
				return this._driver.Entity;
			}
			set
			{
				driver previousValue = this._driver.Entity;
				if (((previousValue != value) 
							|| (this._driver.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._driver.Entity = null;
						previousValue.routes.Remove(this);
					}
					this._driver.Entity = value;
					if ((value != null))
					{
						value.routes.Add(this);
						this._driver_id = value.id;
					}
					else
					{
						this._driver_id = default(int);
					}
					this.SendPropertyChanged("driver");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="warehouse_route1", Storage="_warehouse1", ThisKey="origin_id", OtherKey="id", IsForeignKey=true)]
		public warehouse warehouse1
		{
			get
			{
				return this._warehouse1.Entity;
			}
			set
			{
				warehouse previousValue = this._warehouse1.Entity;
				if (((previousValue != value) 
							|| (this._warehouse1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._warehouse1.Entity = null;
						previousValue.routes1.Remove(this);
					}
					this._warehouse1.Entity = value;
					if ((value != null))
					{
						value.routes1.Add(this);
						this._origin_id = value.id;
					}
					else
					{
						this._origin_id = default(int);
					}
					this.SendPropertyChanged("warehouse1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_parcel_routes(parcel_route entity)
		{
			this.SendPropertyChanging();
			entity.route = this;
		}
		
		private void detach_parcel_routes(parcel_route entity)
		{
			this.SendPropertyChanging();
			entity.route = null;
		}
	}
}
#pragma warning restore 1591
